config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/home', to: 'home#index'
  get '/acessar_paciente', to: 'pacientes#acessar', as: 'acessar_paciente'

  resources :pacientes do
    resource :endereco, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :medicos

  resources :consultas
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/consulta.rb
class Consulta < ApplicationRecord
  belongs_to :paciente
  belongs_to :medico

  validates :data_hora, presence: true
  validate :validar_data_hora

  private

  def validar_data_hora
    errors.add(:data_hora, "Não pode agendar consultas no passado") if data_hora.present? && data_hora < DateTime.current
  end
end

app/models/consultum.rb
class Consulta < ApplicationRecord
  belongs_to :paciente
  belongs_to :medico

  validates :data_hora, presence: true
  validate :validar_data_hora

  private

  def validar_data_hora
    errors.add(:data_hora, "não pode estar no passado") if data_hora.present? && data_hora < DateTime.current
  end
end

app/models/endereco.rb
class Endereco < ApplicationRecord
  belongs_to :paciente

  validates :cep, presence: true, format: { with: /\A\d{8}\z/, message: "deve conter apenas números e ter 8 dígitos" }
  validates :cidade, presence: true
  validates :bairro, presence: true
  validates :logradouro, presence: true
end

app/models/medico.rb
class Medico < ApplicationRecord
  has_many :consultas

  validates :nome_completo, presence: { message: "Informe o nome" }
  validates :cpf, presence: { message: "Informe o CPF" }, uniqueness: { message: "CPF em uso." }, format: { with: /\A\d{11}\z/, message: "O CPF deve conter apenas números e ter 11 dígitos." }
  validates :email, presence: { message: "Informe o email." }, uniqueness: { message: "Este email está em uso." }, format: { with: URI::MailTo::EMAIL_REGEXP, message: "O email é válido." }
  validates :especialidade, presence: { message: "Informe a especialidade." }
  validates :crm, presence: { message: "Informe o CRM" }, uniqueness: { message: "Este CRM já está em uso." }
end

app/models/paciente.rb
class Paciente < ApplicationRecord
  has_one :endereco, dependent: :destroy
  accepts_nested_attributes_for :endereco
  has_many :consultas

  validate :data_nascimento_maior_hoje
  validates :nome_completo, presence: { message: "Informe um nome." }, length: { minimum: 10, message: "Informe um nome válido" }
  validates :cpf, presence: { message: "Informe o CPF." }, uniqueness: { message: "Este CPF já está em uso." }, format: { with: /\A\d{11}\z/, message: "O CPF deve conter apenas números e ter 11 dígitos." }
  validates :email, presence: { message: "O email é obrigatório." }, uniqueness: { message: "Este email já está em uso." }, format: { with: URI::MailTo::EMAIL_REGEXP, message: "Informe um email válido." }

  private

  def data_nascimento_maior_hoje
    errors.add(:data_nascimento, "não pode ser maior que a data de hoje.") if data_nascimento.present? && data_nascimento > Date.current
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/consultas_controller.rb
class ConsultasController < ApplicationController
  def new
    @consulta = Consulta.new
  end

  def create
    @consulta = Consulta.new(consulta_params)
    @paciente = consulta_params[:paciente_id]
    @medico = consulta_params[:medico_id]

    respond_to do |format|
      if @consulta.save
        format.html { redirect_to consulta_url(@consulta), notice: "Consulta criada com sucesso." }
        format.json { render :show, status: :created, location: @consulta }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @consulta.errors, status: :unprocessable_entity }
      end
    end
  end


  def edit
    @consulta = Consulta.find(params[:id])
  end
  def update
    @paciente = consulta_params[:paciente_id]
    respond_to do |format|
      if @consulta.update(consulta_params)
        format.html { redirect_to consulta_url(@consulta), notice: "Consulta atualizada com sucesso." }
        format.json { render :show, status: :ok, location: @consulta }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @consulta.errors, status: :unprocessable_entity }
      end
    end
  end


  def show
    @consulta = Consulta.find(params[:id])
  end

  def index
    @consultas = Consulta.all
  end

  private

  def consulta_params
    params.require(:consulta).permit(:data_hora, :paciente_id, :medico_id)
  end

  def paciente_params
    params.require(:paciente).permit(:nome, :cpf, :email, :nascimento)
  end

  def medico_params
    params.require(:medico).permit(:nome, :cpf, :email, :especialidade, :crm)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/medicos_Controller.rb
class MedicosController < ApplicationController
  before_action :set_medico, only: [:show, :edit, :update, :destroy]

  def index
    @medicos = Medico.all
  end

  def show
  end

  def new
    @medico = Medico.new
  end

  def create
    @medico = Medico.new(medico_params)

    respond_to do |format|
      if @medico.save
        format.html { redirect_to medico_url(@medico), notice: "Medico was successfully created." }
        format.json { render :show, status: :created, location: @medico }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @medico.update(medico_params)
      redirect_to @medico, notice: 'Médico atualizado com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    @medico.destroy
    redirect_to medicos_url, notice: 'Médico removido com sucesso.'
  end

  private

  def set_medico
    @medico = Medico.find(params[:id])
  end

  def medico_params
    params.require(:medico).permit(:nome_completo, :cpf, :email, :especialidade, :crm)
  end
end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  before_action :set_paciente, only: [:show, :edit, :update, :destroy]

  def index
    @pacientes = Paciente.all
  end

  def show
  end

  def new
    @paciente = Paciente.new
  end

  def acessar
    @pacientes = Paciente.all
  end


  def create
    @paciente = Paciente.new(paciente_params)
    @paciente.build_endereco(endereco_params)

    respond_to do |format|
      if @paciente.save
        format.html { redirect_to paciente_url(@paciente), notice: "Paciente criado com sucesso." }
        format.json { render :show, status: :created, location: @paciente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end


  def edit
  end

  def update
    result = @paciente.update(paciente_params)
    result = @paciente.endereco.update(endereco_params) && result

    respond_to do |format|
      if result
        format.html { redirect_to paciente_url(@paciente), notice: "Paciente atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @paciente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @paciente.destroy

    respond_to do |f|
      f.html { redirect_to pacientes_url, notice: "Paciente removido com sucesso" }
      f.json { head :no_content }
    end
  end

  private

  def set_paciente
    @paciente = Paciente.find(params[:id])
  end

  def new_consulta
    @consulta = Consulta.new
  end

  def paciente_params
    params.require(:paciente).permit(:nome_completo, :data_nascimento, :cpf, :email)
  end
  def endereco_params
    params.require(:endereco).permit(:cep, :cidade, :bairro, :logradouro, :complemento, :paciente_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consultas_helper.rb
module ConsultasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/medico_helper.rb
module MedicoHelper
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/views/consultas/_form.html.erb
<%= form_with(model: consulta, url: consulta.persisted? ? consulta_path(consulta) : consultas_path, local: true) do |form| %>
  <% if consulta.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(consulta.errors.count, 'erro') %> impediram a consulta de ser salva:</h2>

      <ul>
        <% consulta.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :data_hora %>
    <%= form.datetime_local_field :data_hora %>
  </div>

  <%= form.hidden_field :paciente_id, value: params[:paciente_id] %>


  <div class="field">
    <%= form.label :medico_id %>
    <%= form.collection_select :medico_id, Medico.all, :id, :nome_completo %>
  </div>

  <div class="actions">
    <%= form.submit 'Salvar' %>
  </div>
<% end %>

app/views/consultas/edit.html.erb
<h1>Editar Consulta</h1>

<%= render 'form', consulta: @consulta %>

<%= link_to 'Voltar', consulta_path(@consulta) %>

app/views/consultas/index.html.erb
<h1>Lista de Consultas</h1>

<table>
  <thead>
  <tr>
    <th>Data e Hora</th>
    <th>Paciente</th>
    <th>Médico</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @consultas.each do |consulta| %>
    <tr>
      <td><%= consulta.data_hora %></td>
      <td><%= consulta.paciente.nome_completo %></td>
      <td><%= consulta.medico.nome_completo %></td>
      <td><%= link_to 'Ver Detalhes', consulta_path(consulta) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Voltar', root_path  %>

app/views/consultas/new.html.erb
<h1>Agendar Consulta</h1>

<%= render 'form', consulta: @consulta %>

<%= link_to 'Voltar', consultas_path %>

app/views/consultas/show.html.erb
<h1>Veja os detalhes da Consulta: </h1>

<p><strong>Data e Hora:</strong> <%= @consulta.data_hora %></p>
<p><strong>Paciente:</strong> <%= @consulta.paciente.nome_completo %></p>
<p><strong>Data de nascimento:</strong> <%= @consulta.paciente.data_nascimento %></p>
<p><strong>Médico:</strong> <%= @consulta.medico.nome_completo %></p>

<%= link_to 'Voltar', medico_path(@consulta.medico) %>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Consulta Sim - Home</title>
</head>
<body>
</br>
</br>
</br>

<div class="container">
  <div class="box">
    <h3>Médico</h3>
    <div class="button-container">
      <a href="<%= medicos_path %>">Acessar medico</a>
      <a href="<%= new_medico_path %>">Novo médico</a>
      <a href="<%= consultas_path %>">Ver todas as consultas</a>

    </div>
  </div>
  </br>
  </br>
  <div class="box">
    <h3>Paciente</h3>
    <div class="button-container">
      <%= link_to 'Acessar', acessar_paciente_path %>
      <%= link_to 'Novo Paciente', new_paciente_path %>
      <a href="<%= pacientes_path %>">Ver todos os pacientes</a>
    </div>
  </div>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Consulta Sim</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <style>
      .home-bar {
          background-color: #007bff;
          color: #fff;
          padding: 10px;
          margin: 0;
          text-align: center;
          border: none;
      }

      .home-bar a {
          text-decoration: none;
          color: #fff;
      }

      .home-bar a:hover {
          text-decoration: underline;
      }
      {
          background-color: #007bff;
      }
  </style>
</head>

<body>
<div class="home-bar">
  <%= link_to root_path do %>
    <h1 style="margin: 0;">Consulta Sim</h1>
  <% end %>
</div>

<%= yield %>
</body>
</html>

app/views/medicos/_form.html.erb
<%= form_with(model: medico, local: true) do |form| %>
  <% if medico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(medico.errors.count, "erro") %> encontrados:</h2>

      <ul>
        <% medico.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome_completo %>
    <%= form.text_field :nome_completo %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :especialidade %>
    <%= form.text_field :especialidade %>
  </div>

  <div class="field">
    <%= form.label :crm %>
    <%= form.text_field :crm %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/medicos/edit.html.erb
<h1>Editando Médico</h1>

<%= render 'form', medico: @medico %>

<br>

<%= link_to 'Cancelar', @medico %> |
<%= link_to 'Voltar', medicos_path %>

app/views/medicos/index.html.erb
<style>
    h1 {
        font-size: 24px;
        margin-bottom: 20px;
    }

    table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 20px;
    }

    th, td {
        padding: 8px;
        text-align: left;
        border-bottom: 1px solid #ddd;
    }

    th {
        font-weight: bold;
    }

    tbody tr:hover {
        background-color: #f5f5f5;
    }

    .btn {
        display: inline-block;
        padding: 6px 12px;
        margin: 2px;
        font-size: 14px;
        font-weight: bold;
        text-align: center;
        text-decoration: none;
        cursor: pointer;
        border: none;
        border-radius: 4px;
        color: #fff;
        background-color: #007bff;
    }

</style>

<h1>Médicos</h1>

<table>
  <thead>
  <tr>
    <th>Nome</th>
    <th>CPF</th>
    <th>E-mail</th>
    <th>Especialidade</th>
    <th>CRM</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
  <% @medicos.each do |medico| %>
    <tr>
      <td><%= medico.nome_completo %></td>
      <td><%= medico.cpf %></td>
      <td><%= medico.email %></td>
      <td><%= medico.especialidade %></td>
      <td><%= medico.crm %></td>
      <td><%= link_to 'Acessar', medico, class: 'btn btn-primary' %></td>
     </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Médico', new_medico_path, class: 'btn btn-primary' %>

app/views/medicos/new.html.erb
<h1>Novo Médico</h1>

<%= render 'form', medico: @medico %>

<br>

<%= link_to 'Voltar', medicos_path %>

app/views/medicos/show.html.erb
<h1> Médico: <%= @medico.nome_completo %></h1>

<p><strong>CPF:</strong> <%= @medico.cpf %></p>
<p><strong>E-mail:</strong> <%= @medico.email %></p>
<p><strong>Especialidade:</strong> <%= @medico.especialidade %></p>
<p><strong>CRM:</strong> <%= @medico.crm %></p>

<br>

<h2>Consultas Agendadas:</h2>
<% if @medico.consultas.any? %>
  <ul>
    <% @medico.consultas.each do |consulta| %>
      <li>
        <%= consulta.paciente.nome_completo %> - <%=  consulta.data_hora.strftime("%d/%m/%Y %H:%M") %>
        <%= link_to 'Ver mais', consulta_path(consulta) %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>Não existem consultas agendadas.</p>
<% end %>
</br>
<%= link_to 'Editar', edit_medico_path(@medico), class: 'btn btn-primary' %> |
<%= link_to 'Voltar', medicos_path, class: 'btn btn-primary' %>

app/views/pacientes/_form.html.erb
<%= form_with(model: paciente) do |form| %>
  <% if paciente.errors.any? || !paciente.endereco.nil? && paciente.endereco.errors.any? %>
    <div style="color: red">
      <ul>
        <% paciente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
        <% paciente.endereco.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div>
    <%= form.label :nome_completo %>
    <%= form.text_field :nome_completo %>
  </div>

  <div>
    <%= form.label :cpf %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :data_nascimento %>
    <%= form.date_field :data_nascimento %>
  </div>

  <%= fields_for(:endereco, paciente.endereco) do |f| %>
    <div>
      <%= f.label :cep %>
      <%= f.text_field :cep %>
    </div>

    <div>
      <%= f.label :cidade %>
      <%= f.text_field :cidade %>
    </div>

    <div>
      <%= f.label :bairro %>
      <%= f.text_field :bairro %>
    </div>

    <div>
      <%= f.label :logradouro %>
      <%= f.text_field :logradouro %>
    </div>

    <div>
      <%= f.label :complemento %>
      <%= f.text_field :complemento %>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pacientes/acessar.html.erb
<link rel="stylesheet" type="text/css" href="style.css">

<h1>Selecione o paciente que deseja acessar</h1>

<ul>
  <% @pacientes.each do |paciente| %>
    <li>
      <%= link_to paciente.nome_completo, paciente %>
    </li>
  <% end %>
</ul>

<%= link_to 'Voltar', root_path %>

app/views/pacientes/edit.html.erb
<h1>Editar Paciente</h1>

<%= form_with(model: @paciente) do |f| %>
  <div class="field">
    <%= f.label :nome_completo %>
    <%= f.text_field :nome_completo %>
  </div>

  <div class="field">
    <%= f.label :data_nascimento %>
    <%= f.date_field :data_nascimento %>
  </div>

  <div class="field">
    <%= f.label :cpf %>
    <%= f.text_field :cpf %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <h2>Endereço</h2>
  <%= f.fields_for :endereco do |endereco_fields| %>
    <div class="field">
      <%= endereco_fields.label :cep %>
      <%= endereco_fields.text_field :cep %>
    </div>

    <div class="field">
      <%= endereco_fields.label :cidade %>
      <%= endereco_fields.text_field :cidade %>
    </div>

    <div class="field">
      <%= endereco_fields.label :bairro %>
      <%= endereco_fields.text_field :bairro %>
    </div>

    <div class="field">
      <%= endereco_fields.label :logradouro %>
      <%= endereco_fields.text_field :logradouro %>
    </div>

    <div class="field">
      <%= endereco_fields.label :complemento %>
      <%= endereco_fields.text_field :complemento %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit 'Salvar' %>
  </div>
<% end %>

<%= link_to 'Voltar', pacientes_path %>

app/views/pacientes/index.html.erb
<link rel="stylesheet" type="text/css" href="style.css">

<h1>Todos os Pacientes</h1>

<ul>
  <% @pacientes.each do |paciente| %>
    <li>
      <%= link_to paciente.nome_completo, paciente %>
    </li>
  <% end %>
</ul>

<%= link_to 'Voltar', root_path %>

app/views/pacientes/new.html.erb
<h1>New paciente</h1>

<%= render "form", paciente: @paciente %>

<br>

<div>
  <%= link_to "Back to pacientes", pacientes_path %>
</div>

app/views/pacientes/show.html.erb
<div class="container">
  <h1>Detalhes do Paciente</h1>

  <p><strong>Nome Completo:</strong> <%= @paciente.nome_completo %></p>
  <p><strong>Data de Nascimento:</strong> <%= @paciente.data_nascimento %></p>
  <p><strong>CPF:</strong> <%= @paciente.cpf %></p>
  <p><strong>Email:</strong> <%= @paciente.email %></p>

  <h2>Endereço</h2>
  <% if @paciente.endereco %>
    <p><strong>CEP:</strong> <%= @paciente.endereco.cep %></p>
    <p><strong>Cidade:</strong> <%= @paciente.endereco.cidade %></p>
    <p><strong>Bairro:</strong> <%= @paciente.endereco.bairro %></p>
    <p><strong>Logradouro:</strong> <%= @paciente.endereco.logradouro %></p>
    <p><strong>Complemento:</strong> <%= @paciente.endereco.complemento %></p>
  <% else %>
    <p>Nenhum endereço cadastrado.</p>
  <% end %>

  <h2>Consultas Agendadas</h2>
  <% if @paciente.consultas.any? %>
    <ul>
      <% @paciente.consultas.each do |consulta| %>
        <li>
          <%= consulta.data_hora.strftime("%d/%m/%Y %H:%M") %> - <%= consulta.medico.nome_completo %>
          <%= link_to 'Ver mais', consulta_path(consulta), method: :delete, data: { confirm: 'Deseja cancelar essa consulta?' } %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>Nenhuma consulta agendada.</p>
  <% end %>

  <div class="actions">
    <%= link_to 'Agendar Consulta', new_consulta_path(paciente_id: @paciente.id), class: 'btn btn-primary', style: 'display: inline-block;' %>
    <%= link_to 'Editar', edit_paciente_path(@paciente), class: 'btn btn-danger', style: 'display: inline-block; margin-left: 10px;' %>
    <%= link_to 'Voltar', pacientes_path, class: 'btn btn-danger', style: 'display: inline-block; margin-left: 10px;' %>
  </div>

</div>